const Enum = require('enum');

const httpResponseCodes = new Enum({
  VALID: 'VALID',
  CREATE_RECORD_SUCCESS: 'CREATE_RECORD_SUCCESS',
  UPDATE_RECORD_SUCCESS: 'UPDATE_RECORD_SUCCESS',
  DELETE_RECORD_SUCCESS: 'DELETE_RECORD_SUCCESS',
  PROCESS_RECORD_SUCCESS: 'PROCESS_RECORD_SUCCESS',
  RETRIEVE_RECORD: 'RETRIEVE_RECORD',
  RETRIEVE_RECORD_LIST: 'RETRIEVE_RECORD_LIST',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  ERROR_PROCESSING: 'ERROR_PROCESSING',
  DATA_PROCESSING_ERROR: 'DATA_PROCESSING_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  ACCEPTED: 'ACCEPTED',

  CREATE_RECORD_FAILED: 'CREATE_RECORD_FAILED',
  RECORD_ALREADY_EXIST: 'RECORD_ALREADY_EXIST',
  RECORD_EMPTY: 'RECORD_EMPTY',
  MEMBERS_EXCEEDED: 'MEMBERS_EXCEED',
});

module.exports = {
  httpResponseCodes,
};
